#!/bin/bash

LSC='./node_modules/.bin/lsc --debug'

mkdir -p build \
  && cd build \
  && rm -rf * 2> /dev/null \
  && yarn add livescript \
  && $LSC -o . -c ../src/*.ls \
  && $LSC -o ./task -c ../src/task/*.ls \
  && $LSC -o ./task/npm -c ../src/task/npm/*.ls \
  && yarn \
  && yarn run build
